### ISSUE TITLE
Adapt to PHP 8

### ISSUE THREAD

**Issue by namnhatpham1995** [oneye/installer#4]
I have fixed problems when running oneye on PHP 8:
https://github.com/namnhatpham1995/installer/tree/fix_error

However, in "package.eyepackage", I have to remove get_magic_quotes_gpc() from file "main.eyecode" in /package/system/system/services/sec to make it run successfully after install.
But when I try to gzip the whole folder package into package.tar.gz and change name to package.eyepackage, the install said "package.eyepackage is corrupted". 

Can you check my fix on the branch and also make change to the package also?

**Comment by lars-sh** [comment]
As the PHP configuration `magic_quotes_gpc` has been removed since PHP 5.4.0, feel free to remove it from the `sec` service.

The sources of the `package.eyepackage` package can be found at https://github.com/oneye/oneye/ . Feel free to raise a Pull Request over there, too.

To handle your error message, please send me a mail with your `package.eyepackage`. I'll try to clarify why your package is claimed to be corrupted.

**Comment by namnhatpham1995** [comment]
Thank you, I have just sent you the package. Please check it for me.

**Comment by lars-sh** [comment]
The error message you get is `Warning: Please, check "./package.eyepackage" since it seems to be corrupted.`, right? Please have a look at the installer's `index.php`. It declares a constant `INSTALL_MD5`, which is used to make sure, that `package.eyepackage` did not corrupt e.g. while uploading files to a web share or similar. You'll need to update the constant's value to the result of `<?php echo md5_file('package.eyepackage'); ?>`.

Please confirm, if that helped you out.

**Comment by namnhatpham1995** [comment]
Thank you, my problem is solved.
